#!/bin/tcsh
#PBS -N asg:msr:np-he
#PBS -l nodes=5:xeon:compute:ppn=8
#PBS -l walltime=02:00:00
#PBS -j oe


set country = nepal

set version = 1.1

set resolution = 0.05

set sector = Agriculture


cd $PBS_O_WORKDIR
mvp2run -m cyclic python-mpi ./runscript.py "$country" "$version" "$resolution" "$sector"
