#!/bin/tcsh
#PBS -N asg:yme-at
#PBS -l nodes=2:xeon:compute:ppn=8
#PBS -l walltime=20:00:00
#PBS -j oe


set project_name = "kfw_grid_clip"

set shape_name = "KFW_ohFiveDecimalDegrees_grid_clipped.shp"

set data_path = "terrestrial_precipitation"

set extract_name = "terrestrial_precipitation"

set file_mask = "precip_YYYY_MM.tif"

set data_base = "/sciclone/aiddata10/REU"

set project_base = "/sciclone/aiddata10/REU"



cd $PBS_O_WORKDIR
mvp2run -m cyclic python-mpi ./runscript.py ./extract.R "$project_name" "$shape_name" "$data_path" "$extract_name" "$file_mask" "$data_base" "$project_base"