#!/bin/tcsh
#PBS -N ad:sg-atap_merge
#PBS -l nodes=1:xeon:compute:ppn=1
#PBS -l walltime=02:00:00
#PBS -j oe

cd $PBS_O_WORKDIR
mvp2run -m cyclic python-mpi ./runscript.py ./extract_merge.R liberia terrestrial_air_temperature
# mvp2run -m cyclic python-mpi ./runscript.py ./extract_merge.R liberia terrestrial_precipitation
