#!/bin/tcsh
#PBS -N asg:se-srtm
#PBS -l nodes=1:xeon:compute:ppn=1
#PBS -l walltime=36:00:00
#PBS -j oe


# extract options: based on temporal type of dataset
# run_option value  | description
# ------------------|------------------------
# 1                 | temporally invariant
# 2                 | year
# 3                 | year month
# 4                 | year day


# temporal type options
# specifies dataset temporal type (see above)
set run_option = 1

# boundary name 
# boundary name which will be used to identify/generate folder in output path
# if boundary file exists in asdf, bnd_name should match asdf name
set bnd_name = "kfw_grid_clip"

# absolute path of boundary file
# includes file with extension
# can be anywhere accessible on /sciclone
set bnd_absolute = "/sciclone/aiddata10/REU/extracts/kfw_grid_clip/shps/KFW_ohFiveDecimalDegrees_grid_clipped.shp"

# folder which contains data
set data_base = "/sciclone/aiddata10/REU/data"

# path relative to data_base
# eg: v4avg_lihgts_x_pct or ltdr_yearly/ndvi_mean
set data_path = "srtm/SRTM_500m.tif"

# dataset name
# if dataset exists in asdf, data_name should match asdf name
set data_name = "srtm_elevation"

# file mask for dataset files
# year must be 4 digits and specified in file mask with "YYYY"
# other chars in mask do not matter as long as they are not "Y"
# file mask must be same length as file names
# eg: (for v4avg_lights_x_pct)  F1xYYYY.v4x.avg_lights_x_pct.tif
set file_mask = "None"

# extract type
# (mean, max, etc.)
set extract_type = "mean"

# parent folder for outputs
# bnd_name folder should exist or will be created in this folder
# extract outputs will be in <output_base>/extracts/<bnd_name>/cache/<data_name>/<extract_type>/extract.csv
set output_base = "/sciclone/aiddata10/REU/extracts"


cd $PBS_O_WORKDIR
mvp2run -m cyclic python-mpi ./runscript.py "$run_option" "$bnd_name" "$bnd_absolute" "$data_base" "$data_path" "$data_name" "$file_mask" "extract_type" "$output_base"
