#!/bin/tcsh
#PBS -N asg:se-srtm
#PBS -l nodes=1:xeon:compute:ppn=1
#PBS -l walltime=36:00:00
#PBS -j oe


# extract options: based on temporal type of dataset
# run_option value  | description
# ------------------|------------------------
# 1                 | temporally invariant
# 2                 | year
# 3                 | year month
# 4                 | year day


# specifies dataset temporal type (see above)
set run_option = 1

# boundary name 
# if boundary is in asdf this must match name used for boundary in asdf
set bnd_name = "kfw_grid_clip"

# absolute path to shapefile 
# can be anywhere accessible on /sciclone
set bnd_absolute = "/sciclone/aiddata10/REU/extracts/kfw_grid_clip/shps/KFW_ohFiveDecimalDegrees_grid_clipped.shp"

# folder which contains data
set data_base = "/sciclone/aiddata10/REU/data"

# path relative to data_base
set data_path = "srtm/SRTM_500m.tif"

# dataset name
# if dataset is in asdf this must match name used for dataset in asdf
set data_name = "srtm_elevation"

# extract type
set extract_type = "mean"

# file mask for dataset files
set file_mask = "None"

# folder where extracts will be output to
# extract outputs will be in <output_base>/extracts/<bnd_name>/cache/<data_name>/<extract_type>/extract.csv
set output_base = "/sciclone/aiddata10/REU/extracts"


cd $PBS_O_WORKDIR
mvp2run -m cyclic python-mpi ./runscript.py "$run_option" "$bnd_name" "$bnd_absolute" "$data_base" "$data_path" "$data_name" "$file_mask" "extract_type" "$output_base"
