#!/bin/tcsh
#PBS -N asg:ye:pytest
#PBS -l nodes=5:xeon:compute:ppn=8
#PBS -l walltime=72:00:00
#PBS -j oe


# set data_path = "v4avg_lights_x_pct"
# set file_mask = "F1xYYYY.v4x.avg_lights_x_pct.tif"

# set data_path = "ltdr_yearly/ndvi_max"
# set extract_name = "ltdr_yearly_max"
# set file_mask = "YYYY.tif"

# set data_path = "gpw_v3"
# set file_mask = "gldsxxag_YYYY.asc"


set project_name = "kfw_grid_clip"

set shape_name = "KFW_ohFiveDecimalDegrees_grid_clipped.shp"
# set shape_name = "testclip.shp"

set data_path = "ltdr_yearly/ndvi_max_mask_lt6k"

set extract_name = "ltdr_yearly_max_mask_lt6k_test"

set file_mask = "YYYY.tif"

set data_base = "/sciclone/aiddata10/REU"

set project_base = "/sciclone/aiddata10/REU"


cd $PBS_O_WORKDIR

mvp2run -m cyclic python-mpi ./runscript.py ./extract.R "$project_name" "$shape_name" "$data_path" "$extract_name" "$file_mask" "$data_base" "$project_base"

