#!/bin/tcsh
#PBS -N asg:ge:kfw-dfcf-w
#PBS -l nodes=1:vortex:compute:ppn=4
#PBS -l walltime=180:00:00
#PBS -j oe


# !!!
# 
# in addition to the script options, remember to update the following:
# 
#  PBS job settings
#       - job name
#       - requested resource type/quantity
#       - walltime
# 
# and if job is running using openmpi (vortex)
#       - number of processors in mpirun commands (-np #)
# 
# !!!


# extract options: based on temporal type of dataset
# run_option value  | description
# ------------------|------------------------
# 1                 | temporally invariant
# 2                 | year
# 3                 | year month
# 4                 | year day


# temporal type options
# specifies dataset temporal type (see above)
# set run_option = 1

# boundary name which will be used to identify/generate folder in output path
# if boundary file exists in asdf, bnd_name should match asdf "name"
# set bnd_name = "wb_vfm_matching_ibas"

# absolute path of boundary file
# includes file with extension
# can be anywhere accessible on /sciclone
# set bnd_absolute = "/sciclone/aiddata10/REU/extracts/wb_vfm_matching_ibas/shps/matching_ibas_proj.shp"

# folder which contains data
# set data_base = "/sciclone/aiddata10/REU/data"

# path relative to data_base
# eg: v4avg_lihgts_x_pct or ltdr_yearly/ndvi_mean
# set data_path = "srtm_elevation/SRTM_500m.tif"

# dataset name
# if dataset exists in asdf, data_name should match asdf name
# set data_name = "srtm_elevation"

# dataset mini name
# 4 character (alphanumeric) string used to identify dataset in fields names
# if dataset exists in asdf, data_mini should match asdf "mini_name"
# if dataset is not in asdf you can set data_mini to "None" to use same value as data_name
# set data_mini = "selv"

# file mask for dataset files
# year must be 4 digits and specified in file mask with "YYYY"
# other chars in mask do not matter as long as they are not "Y"
# file mask must be same length as file names
# eg: (for v4avg_lights_x_pct)  F1xYYYY.v4x.avg_lights_x_pct.tif
# set file_mask = "None"

# extract type
# (mean, max, etc.)
# set extract_type = "mean"

# parent folder for outputs
# bnd_name folder should exist or will be created in this folder
# extract outputs will be in <output_base>/extracts/<bnd_name>/cache/<data_name>/<extract_type>/extract.csv
# set output_base = "/sciclone/aiddata10/REU/extracts"


set bnd_name = "kfw_grid_clipw"
set bnd_absolute = "/sciclone/aiddata10/REU/projects/kfw_grid_clip/shps/KFW_ohFiveDecimalDegrees_grid_clipped.shp"
set output_base = "/sciclone/aiddata10/REU/extracts"


# set run_option = 1
# set data_base = "/sciclone/aiddata10/REU/data"
# set data_path = "regional/south_america/DistanceFromLoggingCenters.tif"
# set data_name = "dist_from_logging_center"
# set data_mini = "dflc"
# set file_mask = "None"
# set extract_type = "mean"

# set run_option = 1
# set data_base = "/sciclone/aiddata10/REU/data"
# set data_path = "regional/south_america/DistFromRailways.tif"
# set data_name = "dist_from_railways"
# set data_mini = "dfrw"
# set file_mask = "None"
# set extract_type = "mean"

# set run_option = 1
# set data_base = "/sciclone/aiddata10/REU/data"
# set data_path = "regional/south_america/DistFromMiningInterests.tif"
# set data_name = "dist_from_mining_interests"
# set data_mini = "dfmi"
# set file_mask = "None"
# set extract_type = "mean"

# set run_option = 1
# set data_base = "/sciclone/aiddata10/REU/data"
# set data_path = "regional/south_america/Dist_Conservation_StateUnits.tif"
# set data_name = "dist_from_conservation_state_units"
# set data_mini = "dfcs"
# set file_mask = "None"
# set extract_type = "mean"

set run_option = 1
set data_base = "/sciclone/aiddata10/REU/data"
set data_path = "regional/south_america/Dist_Conservation_FederalUnits.tif"
set data_name = "dist_from_conservation_federal_units"
set data_mini = "dfcf"
set file_mask = "None"
set extract_type = "mean"


cd $PBS_O_WORKDIR

# mvp2run -m cyclic python-mpi ./runscript.py "$run_option" "$bnd_name" "$bnd_absolute" "$data_base" "$data_path" "$data_name" "$data_mini" "$file_mask" "$extract_type" "$output_base"

mpirun --mca mpi_warn_on_fork 0 -np 1 python-mpi ./runscript.py "$run_option" "$bnd_name" "$bnd_absolute" "$data_base" "$data_path" "$data_name" "$data_mini" "$file_mask" "$extract_type" "$output_base"
