#!/bin/tcsh
#PBS -N asg:ex:kfw-at41
#PBS -l nodes=4:xeon:compute:ppn=8
#PBS -l walltime=180:00:00
#PBS -j oe


set bnd_name = "kfw"
set bnd_absolute = "/sciclone/aiddata10/REU/projects/kfw/shps/terra_indigenaPolygon_id.shp"
set output_base = "/sciclone/aiddata10/REU/extracts"
set extract_method = "rpy2"


set run_option = 3
set data_base = "/sciclone/aiddata10/REU/data/rasters/external/global"
set data_path = "terrestrial_air_temperature_v4.01"
set data_name = "terrestrial_air_temperature_v4.01"
set data_mini = "at41"
set file_mask = "yyyy/air_temp_YYYY_MM.tif"
set extract_type = "mean"

# set run_option = 3
# set data_base = "/sciclone/aiddata10/REU/data/rasters/external/global"
# set data_path = "terrestrial_precipitation_v4.01"
# set data_name = "terrestrial_precipitation_v4.01"
# set data_mini = "pc41"
# set file_mask = "yyyy/precip_YYYY_MM.tif"
# set extract_type = "mean"


# set run_option = 1
# set data_base = "/sciclone/aiddata10/REU/data"
# set data_path = "regional/south_america/DistanceFromLoggingCenters.tif"
# set data_name = "dist_from_logging_center"
# set data_mini = "dflc"
# set file_mask = "None"
# set extract_type = "mean"

# set run_option = 1
# set data_base = "/sciclone/aiddata10/REU/data"
# set data_path = "regional/south_america/DistFromRailways.tif"
# set data_name = "dist_from_railways"
# set data_mini = "dfrw"
# set file_mask = "None"
# set extract_type = "mean"

# set run_option = 1
# set data_base = "/sciclone/aiddata10/REU/data"
# set data_path = "regional/south_america/DistFromMiningInterests.tif"
# set data_name = "dist_from_mining_interests"
# set data_mini = "dfmi"
# set file_mask = "None"
# set extract_type = "mean"

# set run_option = 1
# set data_base = "/sciclone/aiddata10/REU/data"
# set data_path = "regional/south_america/Dist_Conservation_StateUnits.tif"
# set data_name = "dist_from_conservation_state_units"
# set data_mini = "dfcs"
# set file_mask = "None"
# set extract_type = "mean"

# set run_option = 1
# set data_base = "/sciclone/aiddata10/REU/data"
# set data_path = "regional/south_america/Dist_Conservation_FederalUnits.tif"
# set data_name = "dist_from_conservation_federal_units"
# set data_mini = "dfcf"
# set file_mask = "None"
# set extract_type = "mean"


cd $PBS_O_WORKDIR

mvp2run -m cyclic python-mpi ../runscript.py "$run_option" "$bnd_name" "$bnd_absolute" "$data_base" "$data_path" "$data_name" "$data_mini" "$file_mask" "$extract_type" "$output_base" "$extract_method"

# mpirun --mca mpi_warn_on_fork 0 -np 12 python-mpi ./runscript.py "$run_option" "$bnd_name" "$bnd_absolute" "$data_base" "$data_path" "$data_name" "$data_mini" "$file_mask" "$extract_type" "$output_base" "$extract_method"
