#!/bin/tcsh
#PBS -N asg:ex:wb-pc41
#PBS -l nodes=5:xeon:compute:ppn=8
#PBS -l walltime=72:00:00
#PBS -j oe


set bnd_name = "wb_vfm_matching_ibas"
set bnd_absolute = "/sciclone/aiddata10/REU/extracts/wb_vfm_matching_ibas/shps/matching_ibas_proj.shp"
set output_base = "/sciclone/aiddata10/REU/extracts"
set extract_method = "rpy2"


# set run_option = 1
# set data_base = "/sciclone/aiddata10/REU/data/rasters/external/global"
# set data_path = "dist_to_all_rivers/world_allrivsCOMP.tif"
# set data_name = "dist_to_all_rivers"
# set data_mini = "dari"
# set file_mask = "None"
# set extract_type = "mean"

# set run_option = 1
# set data_base = "/sciclone/aiddata10/REU/data/rasters/external/global"
# set data_path = "dist_to_big_rivers/world_bigrivCOMP.tif"
# set data_name = "dist_to_big_rivers"
# set data_mini = "dbri"
# set file_mask = "None"
# set extract_type = "mean"

# set run_option = 1
# set data_base = "/sciclone/aiddata10/REU/data/rasters/external/global"
# set data_path = "dist_to_roads/WorldRoadsCOMP.tif"
# set data_name = "dist_to_roads"
# set data_mini = "droa"
# set file_mask = "None"
# set extract_type = "mean"


# set run_option = 1
# set data_base = "/sciclone/aiddata10/REU/data/rasters/external/global"
# set data_path = "srtm_elevation/SRTM_500m.tif"
# set data_name = "srtm_elevation"
# set data_mini = "selv"
# set file_mask = "None"
# set extract_type = "mean"

# set run_option = 1
# set data_base = "/sciclone/aiddata10/REU/data/rasters/external/global"
# set data_path = "srtm_slope/SRTM_500m_slope.tif"
# set data_name = "srtm_slope"
# set data_mini = "sslp"
# set file_mask = "None"
# set extract_type = "mean"

# set run_option = 1
# set data_base = "/sciclone/aiddata10/REU/data/rasters/external/global"
# set data_path = "accessibility_map/access_50k.tif"
# set data_name = "accessibility_map"
# set data_mini = "am50"
# set file_mask = "None"
# set extract_type = "mean"

# set run_option = 2
# set data_base = "/sciclone/aiddata10/REU/data/rasters/external/global"
# set data_path = "gpw_v3"
# set data_name = "gpw_v3"
# set data_mini = "gpw3"
# set file_mask = "gldsxxag_YYYY.asc"
# set extract_type = "mean"

# set run_option = 2
# set data_base = "/sciclone/aiddata10/REU/data/rasters/external/global"
# set data_path = "ltdr_yearly/ndvi_max_mask_lt6k"
# set data_name = "ndvi_max_mask_lt6k"
# set data_mini = "nm6k"
# set file_mask = "YYYY.tif"
# set extract_type = "mean"

# set run_option = 2
# set data_base = "/sciclone/aiddata10/REU/data/rasters/external/global"
# set data_path = "v4avg_lights_x_pct"
# set data_name = "v4avg_lights_x_pct"
# set data_mini = "alp4"
# set file_mask = "FxxYYYY.v4x.avg_lights_x_pct.tif"
# set extract_type = "mean"

# set run_option = 3
# set data_base = "/sciclone/aiddata10/REU/data/rasters/external/global"
# set data_path = "terrestrial_air_temperature_v4.01"
# set data_name = "terrestrial_air_temperature_v4.01"
# set data_mini = "at41"
# set file_mask = "yyyy/air_temp_YYYY_MM.tif"
# set extract_type = "mean"

set run_option = 3
set data_base = "/sciclone/aiddata10/REU/data/rasters/external/global"
set data_path = "terrestrial_precipitation_v4.01"
set data_name = "terrestrial_precipitation_v4.01"
set data_mini = "pc41"
set file_mask = "yyyy/precip_YYYY_MM.tif"
set extract_type = "mean"


cd $PBS_O_WORKDIR

mvp2run -m cyclic python-mpi ../runscript.py "$run_option" "$bnd_name" "$bnd_absolute" "$data_base" "$data_path" "$data_name" "$data_mini" "$file_mask" "$extract_type" "$output_base" "$extract_method"

# mpirun --mca mpi_warn_on_fork 0 -np 1 python-mpi ../runscript.py "$run_option" "$bnd_name" "$bnd_absolute" "$data_base" "$data_path" "$data_name" "$data_mini" "$file_mask" "$extract_type" "$output_base" "$extract_method"

