#!/bin/tcsh
#PBS -N ad:sg-ye:ntl
#PBS -l nodes=6:xeon:compute:ppn=8
#PBS -l walltime=24:00:00
#PBS -j oe

project_name="liberia"

shape_name="LBR_adm3.shp"

data_path="v4avg_lights_x_pct"

extract_name="v4avg_lights_x_pct"

file_mask="F1xYYYY.v4x.avg_lights_x_pct.tif"

data_base="/sciclone/aiddata10/REU"

project_base="/sciclone/aiddata10/REU"


cd $PBS_O_WORKDIR
mvp2run -m cyclic python-mpi ./runscript.py ./yearly_extract_hpc.R "$project_name" "$shape_name" "$data_path" "$extract_name" "$file_mask" "$data_base" "$project_base"