#!/bin/bash

mkdir -p chain

for year in $(seq 1983 1985); do

	job="$job"

	cat jobscript_base > "jobs"/jobscript_"$year"

	mpi_str="mvp2run -m cyclic python-mpi ./runscript.py ./extract_hpc.R"

	echo "$mpi_str" "$year" >> "$job"

	qsub "$job"

done
