#!/bin/bash

mkdir -p "jobs"
cd "jobs"

for year in $(seq 2003 2014); do

	job=jobscript_"$year"

	cat ../jobscript_base > "$job"

	mpi_str="mvp2run -m cyclic python-mpi ../runscript.py ../extract_hpc.R"

	echo "$mpi_str" "$year" >> "$job"

	qsub "$job"

done
