#!/bin/tcsh
#PBS -N asg:ex:wb-dari
#PBS -l nodes=1:vortex:compute:ppn=1
#PBS -l walltime=02:00:00
#PBS -j oe


# !!!
# 
# in addition to the script options, remember to update the following:
# 
#  PBS job settings
#       - job name
#       - requested resource type/quantity
#       - walltime
# 
# and if job is running using openmpi (vortex)
#       - number of processors in mpirun commands (-np #)
# 
# !!!


# boundary name which will be used to identify/generate folder in output path
# if boundary file exists in asdf, bnd_name should match asdf "name"
# set bnd_name = "wb_vfm_matching_ibas"

# absolute path of boundary file
# includes file with extension
# can be anywhere accessible on /sciclone
# set bnd_absolute = "/sciclone/aiddata10/REU/extracts/wb_vfm_matching_ibas/shps/matching_ibas_proj.shp"

# folder which contains data
# set data_base = "/sciclone/aiddata10/REU/data"

# path relative to data_base
# eg: v4avg_lihgts_x_pct or ltdr_yearly/ndvi_mean
# set data_path = "srtm_elevation/SRTM_500m.tif"

# dataset name
# if dataset exists in asdf, data_name should match asdf name
# set data_name = "srtm_elevation"

# dataset mini name
# 4 character (alphanumeric) string used to identify dataset in fields names
# if dataset exists in asdf, data_mini should match asdf "mini_name"
# if dataset is not in asdf you can set data_mini to "None" to use same value as data_name
# set data_mini = "selv"

# file mask for dataset files
# year must be 4 digits and specified in file mask with "YYYY"
# other chars in mask do not matter as long as they are not "Y"
# file mask must be same length as file names
# eg: (for v4avg_lights_x_pct)  F1xYYYY.v4x.avg_lights_x_pct.tif
# set file_mask = "None"

# parent folder for outputs
# bnd_name folder should exist or will be created in this folder
# extract outputs will be in <output_base>/extracts/<bnd_name>/cache/<data_name>/<extract_type>/extract.csv
# set output_base = "/sciclone/aiddata10/REU/extracts"

# extract method
# (rscript, rpy2, python)
# set extract_method = "rscript"


set extract_method = "python"
set bnd_absolute = "/sciclone/aiddata10/REU/extracts/wb_pc1/shps/wb_pc1.geojson"
set bnd_name = "wb_pc1"
set output_base = "/sciclone/aiddata10/REU/extracts"


set file_mask = "None"
set extract_type = "mean"
set data_base = "/sciclone/aiddata10/REU/data/rasters/external/global/dist_to_all_rivers/world_allrivsCOMP.tif"
set data_name = "dist_to_all_rivers"
set data_mini = "dari"



cd $PBS_O_WORKDIR

# mvp2run -m cyclic python-mpi ./runscript.py "$extract_method" "$bnd_absolute" "$bnd_name" "$file_mask" "$extract_type" "$data_base" "$data_name" "$data_mini" "$output_base" 

mpirun --mca mpi_warn_on_fork 0 -np 1 python-mpi ./runscript.py "$extract_method" "$bnd_absolute" "$bnd_name" "$file_mask" "$extract_type" "$data_base" "$data_name" "$data_mini" "$output_base" 

