#!/bin/bash


# --------------------------------------------------
# example jobscript output:

# #!/bin/tcsh
# #PBS -N ad:sg-ltdr_ex
# #PBS -l nodes=3:xeon:compute:ppn=8
# #PBS -l walltime=02:30:00
# #PBS -j oe

# cd $PBS_O_WORKDIR
# mvp2run -m cyclic python-mpi ../runscript.py ../extract.R 1981

# --------------------------------------------------

# project_name="kfw"

# shape_name="terra_indegenaPolygon_id.shp"

# data_path="ltdr.nascom.nasa.gov/allData/Ver4/ndvi"

# extract_name="ltdr_ndvi"

# file_mask="AVH13C1.A1984DDD.N07.004.2013225115505.tif"

# data_base="/sciclone/aiddata10/REU"

# project_base="/sciclone/aiddata10/REU"


project_name="nepal"

shape_name="ADM3/NPL_adm3.shp"

data_path="ltdr.nascom.nasa.gov/allData/Ver4/ndvi"

extract_name="ltdr_ndvi"

file_mask="AVH13C1.A1984DDD.N07.004.2013225115505.tif"

data_base="/sciclone/aiddata10/REU"

project_base="/sciclone/aiddata10/REU"


# for a range of consecutive years assign a start and end year
# start_year and end_year values are included in range
# to cover a single year, make start_year and end_year the same
start_year=1982
end_year=1982

range=$(seq $start_year $end_year)


# for non-consecutive years use manual range
# example: range="1982 1989 1995"
# range=""


mkdir -p "jobs"
cd "jobs"

for year in $range; do

    job=jobscript_"$year"

    cat ../jobscript_base > "$job"

    mpi_str="mvp2run -m cyclic python-mpi ../runscript.py ../extract.R"

    echo "$mpi_str" "$project_name" "$shape_name" "$data_path" "$extract_name" "$file_mask" "$data_base" "$project_base" "$year" >> "$job"

    qsub "$job"

    # could add prev_job = qsub "$sub" -DEPENDS ON PREVJOB OK
    # to run years sequentially (prevent continuing if a year has an error)

done

# call merge script
# python ../merge.py "$project_base"/projects/"$project_name"/extracts/"$extract_name"  
