#!/bin/tcsh
#PBS -N asdf-update
#PBS -l nodes=1:vortex:ppn=3
#PBS -l walltime=180:00:00
#PBS -j oe

cd $PBS_O_WORKDIR


# copy files
src="${HOME}"/active/"$branch"



mpirun --mca mpi_warn_on_fork 0 -np 1 python-mpi ./update_trackers.py
mpirun --mca mpi_warn_on_fork 0 -np 1 python-mpi ./update_extract_list.py
mpirun --mca mpi_warn_on_fork 0 -np 1 python-mpi ./update_msr_list.py


